---
name: CAM-DBF
version: 1.01
author:
  - Clotho Advanced Media Inc., I<cpan@clotho.com>
abstract: Perl extension for reading and writing dBASE III DBF files
license: perl
requires:
  FileHandle: 2.0
  Getopt::Long: 2.0
  Pod::Usage: 1.0
build_requires:
  Test::More: 0.01
provides:
  CAM::DBF:
    file: lib/CAM/DBF.pm
    version: 1.01
generated_by: Module::Build version 0.2609
